services:
  - type: web
    name: stress-detector-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir code app:app --timeout 120 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
